kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${{ values.repo_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.repo_name }}
  template:
    metadata:
      labels:
        app: ${{ values.repo_name }}
    spec:
      containers:
        - name: ${{ values.repo_name }}
          image: quay.io/${{ values.image_namespace }}/${{ values.repo_name }}:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
