---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.component_id }}-preprod
  namespace: janus-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: janus
  source:
    repoURL: ${{ values.destination }}
    targetRevision: HEAD
    path: ./helm/app
    helm:
      parameters:
      - name: namespace.name
        value: ${{ values.component_id }}-preprod
      - name: environment
        value: preprod
      - name: image.tag
        value: preprod
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.component_id }}-preprod
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
