kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${{ values.repo_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.repo_name }}
  template:
    metadata:
      labels:
        app: ${{ values.repo_name }}
    spec:
      containers:
        - name: ${{ values.repo_name }}
          image: ${{values.image_repository}}/${{ values.image_url }}/${{ values.repo_name }}:latest
          ports:
            - name: http-${{ values.port }}
              containerPort: ${{ values.port }}
              protocol: TCP
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
